// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package database

import (
	"context"
)

const deleteAllGroups = `-- name: DeleteAllGroups :exec
DELETE FROM groups
`

func (q *Queries) DeleteAllGroups(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllGroups)
	return err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}
