// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserBalanceByGroup = `-- name: GetUserBalanceByGroup :one
SELECT users_groups.group_id AS group_id, SUM(payments.amount) - SUM(splits.amount) AS balance FROM splits
INNER JOIN expenses ON splits.expense_id = expenses.id
INNER JOIN users_groups ON expenses.group_id = users_groups.group_id
INNER JOIN payments ON payments.group_id = users_groups.group_id AND payments.paid_to = $1
WHERE users_groups.user_id = $1
GROUP BY users_groups.group_id
`

type GetUserBalanceByGroupRow struct {
	GroupID uuid.UUID
	Balance int32
}

func (q *Queries) GetUserBalanceByGroup(ctx context.Context, paidTo uuid.NullUUID) (GetUserBalanceByGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBalanceByGroup, paidTo)
	var i GetUserBalanceByGroupRow
	err := row.Scan(&i.GroupID, &i.Balance)
	return i, err
}
