// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, created_at, updated_at, group_id, created_by, paid_by, description)
VALUES (
    GEN_RANDOM_UUID(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
) RETURNING id, created_by, group_id, created_at, updated_at, paid_by, description
`

type CreateExpenseParams struct {
	GroupID     uuid.UUID
	CreatedBy   uuid.NullUUID
	PaidBy      uuid.NullUUID
	Description string
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.GroupID,
		arg.CreatedBy,
		arg.PaidBy,
		arg.Description,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidBy,
		&i.Description,
	)
	return i, err
}

const createSplit = `-- name: CreateSplit :one
INSERT INTO splits (id, created_at, updated_at, expense_id, user_id, amount)
VALUES (
    GEN_RANDOM_UUID(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
) RETURNING id, created_at, updated_at, expense_id, user_id, amount
`

type CreateSplitParams struct {
	ExpenseID uuid.UUID
	UserID    uuid.NullUUID
	Amount    string
}

func (q *Queries) CreateSplit(ctx context.Context, arg CreateSplitParams) (Split, error) {
	row := q.db.QueryRowContext(ctx, createSplit, arg.ExpenseID, arg.UserID, arg.Amount)
	var i Split
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :one
DELETE FROM expenses
WHERE id = $1
RETURNING id, created_by, group_id, created_at, updated_at, paid_by, description
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRowContext(ctx, deleteExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidBy,
		&i.Description,
	)
	return i, err
}

const deleteSplit = `-- name: DeleteSplit :one
DELETE FROM splits
WHERE id = $1
RETURNING id, created_at, updated_at, expense_id, user_id, amount
`

func (q *Queries) DeleteSplit(ctx context.Context, id uuid.UUID) (Split, error) {
	row := q.db.QueryRowContext(ctx, deleteSplit, id)
	var i Split
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
	)
	return i, err
}

const getExpensesByGroup = `-- name: GetExpensesByGroup :many
SELECT id, created_by, group_id, created_at, updated_at, paid_by, description FROM expenses
WHERE group_id = $1
`

func (q *Queries) GetExpensesByGroup(ctx context.Context, groupID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidBy,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET paid_by = $2, description = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, created_by, group_id, created_at, updated_at, paid_by, description
`

type UpdateExpenseParams struct {
	ID          uuid.UUID
	PaidBy      uuid.NullUUID
	Description string
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense, arg.ID, arg.PaidBy, arg.Description)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidBy,
		&i.Description,
	)
	return i, err
}
