// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, created_at, updated_at, owner)
VALUES (GEN_RANDOM_UUID(), $1, NOW(), NOW(), $2)
RETURNING id, name, created_at, updated_at, owner
`

type CreateGroupParams struct {
	Name  string
	Owner uuid.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.Owner)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
	)
	return i, err
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at, owner
`

type UpdateGroupNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroupName, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
	)
	return i, err
}
