// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, owner)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at, owner
`

type CreateGroupParams struct {
	Name  string
	Owner uuid.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.Owner)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :one
DELETE FROM groups
WHERE id = $1
RETURNING id, name, created_at, updated_at, owner
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, deleteGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_at, updated_at, owner FROM groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
	)
	return i, err
}

const getGroupsByUser = `-- name: GetGroupsByUser :many
SELECT groups.id, groups.name, groups.created_at, groups.updated_at, groups.owner FROM groups
INNER JOIN users_groups ON groups.id = users_groups.group_id
WHERE users_groups.user_id = $1
`

func (q *Queries) GetGroupsByUser(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOtherUsersInGroup = `-- name: GetOtherUsersInGroup :many
SELECT users_groups.group_id AS group_id, users.id, users.username, users.hashed_password, users.created_at, users.updated_at FROM users
INNER JOIN users_groups ON users.id = users_groups.user_id
WHERE group_id = $1 AND users.id != $2
`

type GetOtherUsersInGroupParams struct {
	GroupID uuid.UUID
	ID      uuid.UUID
}

type GetOtherUsersInGroupRow struct {
	GroupID        uuid.UUID
	ID             uuid.UUID
	Username       string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetOtherUsersInGroup(ctx context.Context, arg GetOtherUsersInGroupParams) ([]GetOtherUsersInGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, getOtherUsersInGroup, arg.GroupID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOtherUsersInGroupRow
	for rows.Next() {
		var i GetOtherUsersInGroupRow
		if err := rows.Scan(
			&i.GroupID,
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroup = `-- name: GetUserGroup :one
SELECT id, user_id, group_id FROM users_groups
WHERE user_id = $1 AND group_id = $2
`

type GetUserGroupParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetUserGroup(ctx context.Context, arg GetUserGroupParams) (UsersGroup, error) {
	row := q.db.QueryRowContext(ctx, getUserGroup, arg.UserID, arg.GroupID)
	var i UsersGroup
	err := row.Scan(&i.ID, &i.UserID, &i.GroupID)
	return i, err
}

const getUsersByGroup = `-- name: GetUsersByGroup :many
SELECT users.id, users.username, users.hashed_password, users.created_at, users.updated_at FROM users
INNER JOIN users_groups ON users.id = users_groups.user_id
WHERE users_groups.group_id = $1
`

func (q *Queries) GetUsersByGroup(ctx context.Context, groupID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at, owner
`

type UpdateGroupNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroupName, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
	)
	return i, err
}
