// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Debt struct {
	ID        uuid.UUID
	ExpenseID uuid.UUID
	OwedBy    uuid.NullUUID
	OwedTo    uuid.NullUUID
	Amount    decimal.Decimal
}

type Expense struct {
	ID            uuid.UUID
	PaidBy        uuid.NullUUID
	Description   string
	TransactionID uuid.UUID
	Amount        decimal.Decimal
}

type Group struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Owner     uuid.UUID
}

type Payment struct {
	ID            uuid.UUID
	PaidBy        uuid.NullUUID
	PaidTo        uuid.NullUUID
	Amount        decimal.Decimal
	TransactionID uuid.UUID
}

type Transaction struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.NullUUID
	GroupID   uuid.UUID
	Kind      string
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UsersGroup struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	GroupID uuid.UUID
}
