// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, created_at, updated_at, group_id, created_by, paid_by, paid_to, amount)
VALUES (
    GEN_RANDOM_UUID(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, created_at, updated_at, group_id, created_by, paid_by, paid_to, amount
`

type CreatePaymentParams struct {
	GroupID   uuid.UUID
	CreatedBy uuid.NullUUID
	PaidBy    uuid.NullUUID
	PaidTo    uuid.NullUUID
	Amount    string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.GroupID,
		arg.CreatedBy,
		arg.PaidBy,
		arg.PaidTo,
		arg.Amount,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.PaidTo,
		&i.Amount,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :one
DELETE FROM payments
WHERE id = $1
RETURNING id, created_at, updated_at, group_id, created_by, paid_by, paid_to, amount
`

func (q *Queries) DeletePayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, deletePayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.PaidTo,
		&i.Amount,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET amount = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, group_id, created_by, paid_by, paid_to, amount
`

type UpdatePaymentParams struct {
	ID     uuid.UUID
	Amount string
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePayment, arg.ID, arg.Amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.PaidTo,
		&i.Amount,
	)
	return i, err
}
