// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (expense_id, owed_to, owed_by, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, expense_id, owed_by, owed_to, amount
`

type CreateDebtParams struct {
	ExpenseID uuid.UUID
	OwedTo    uuid.NullUUID
	OwedBy    uuid.NullUUID
	Amount    decimal.Decimal
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRowContext(ctx, createDebt,
		arg.ExpenseID,
		arg.OwedTo,
		arg.OwedBy,
		arg.Amount,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OwedBy,
		&i.OwedTo,
		&i.Amount,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (transaction_id, paid_by, description, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, paid_by, description, transaction_id, amount
`

type CreateExpenseParams struct {
	TransactionID uuid.UUID
	PaidBy        uuid.NullUUID
	Description   string
	Amount        decimal.Decimal
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.TransactionID,
		arg.PaidBy,
		arg.Description,
		arg.Amount,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.PaidBy,
		&i.Description,
		&i.TransactionID,
		&i.Amount,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (transaction_id, paid_by, paid_to, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, paid_by, paid_to, amount, transaction_id
`

type CreatePaymentParams struct {
	TransactionID uuid.UUID
	PaidBy        uuid.NullUUID
	PaidTo        uuid.NullUUID
	Amount        decimal.Decimal
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.TransactionID,
		arg.PaidBy,
		arg.PaidTo,
		arg.Amount,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaidBy,
		&i.PaidTo,
		&i.Amount,
		&i.TransactionID,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (group_id, created_by, kind)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, created_by, group_id, kind
`

type CreateTransactionParams struct {
	GroupID   uuid.UUID
	CreatedBy uuid.NullUUID
	Kind      string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, arg.GroupID, arg.CreatedBy, arg.Kind)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.GroupID,
		&i.Kind,
	)
	return i, err
}

const deleteDebtsByExpense = `-- name: DeleteDebtsByExpense :exec
DELETE FROM debts
WHERE expense_id = $1
`

func (q *Queries) DeleteDebtsByExpense(ctx context.Context, expenseID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDebtsByExpense, expenseID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getExpensesByGroup = `-- name: GetExpensesByGroup :many
SELECT expenses.id, expenses.paid_by, expenses.description, expenses.transaction_id, expenses.amount FROM expenses
INNER JOIN transactions ON expenses.transaction_id = transactions.id
WHERE transactions.group_id = $1
ORDER BY transactions.updated_at
`

func (q *Queries) GetExpensesByGroup(ctx context.Context, groupID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.PaidBy,
			&i.Description,
			&i.TransactionID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsByGroup = `-- name: GetPaymentsByGroup :many
SELECT payments.id, paid_by, paid_to, amount, transaction_id, transactions.id, created_at, updated_at, created_by, group_id, kind FROM payments
INNER JOIN transactions ON payments.transaction_id = transactions.id
WHERE transactions.group_id = $1
ORDER BY transactions.updated_at
`

type GetPaymentsByGroupRow struct {
	ID            uuid.UUID
	PaidBy        uuid.NullUUID
	PaidTo        uuid.NullUUID
	Amount        decimal.Decimal
	TransactionID uuid.UUID
	ID_2          uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CreatedBy     uuid.NullUUID
	GroupID       uuid.UUID
	Kind          string
}

func (q *Queries) GetPaymentsByGroup(ctx context.Context, groupID uuid.UUID) ([]GetPaymentsByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentsByGroupRow
	for rows.Next() {
		var i GetPaymentsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.PaidBy,
			&i.PaidTo,
			&i.Amount,
			&i.TransactionID,
			&i.ID_2,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.GroupID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, created_at, updated_at, created_by, group_id, kind FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.GroupID,
		&i.Kind,
	)
	return i, err
}

const getTransactionsByGroup = `-- name: GetTransactionsByGroup :many
SELECT id, created_at, updated_at, created_by, group_id, kind FROM transactions
WHERE group_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetTransactionsByGroup(ctx context.Context, groupID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.GroupID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :one
UPDATE debts
SET amount = $2
WHERE id = $1
RETURNING id, expense_id, owed_by, owed_to, amount
`

type UpdateDebtParams struct {
	ID     uuid.UUID
	Amount decimal.Decimal
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error) {
	row := q.db.QueryRowContext(ctx, updateDebt, arg.ID, arg.Amount)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OwedBy,
		&i.OwedTo,
		&i.Amount,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET paid_by = $2, description = $3, amount = $4
WHERE id = $1
RETURNING id, paid_by, description, transaction_id, amount
`

type UpdateExpenseParams struct {
	ID          uuid.UUID
	PaidBy      uuid.NullUUID
	Description string
	Amount      decimal.Decimal
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.ID,
		arg.PaidBy,
		arg.Description,
		arg.Amount,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.PaidBy,
		&i.Description,
		&i.TransactionID,
		&i.Amount,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET amount = $2, paid_by = $3, paid_to = $4
WHERE id = $1
RETURNING id, paid_by, paid_to, amount, transaction_id
`

type UpdatePaymentParams struct {
	ID     uuid.UUID
	Amount decimal.Decimal
	PaidBy uuid.NullUUID
	PaidTo uuid.NullUUID
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePayment,
		arg.ID,
		arg.Amount,
		arg.PaidBy,
		arg.PaidTo,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaidBy,
		&i.PaidTo,
		&i.Amount,
		&i.TransactionID,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, created_by, group_id, kind
`

func (q *Queries) UpdateTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.GroupID,
		&i.Kind,
	)
	return i, err
}
