// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_groups.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserGroup = `-- name: CreateUserGroup :one
INSERT INTO users_groups (id, user_id, group_id)
VALUES (GEN_RANDOM_UUID(), $1, $2)
RETURNING id, user_id, group_id
`

type CreateUserGroupParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UsersGroup, error) {
	row := q.db.QueryRowContext(ctx, createUserGroup, arg.UserID, arg.GroupID)
	var i UsersGroup
	err := row.Scan(&i.ID, &i.UserID, &i.GroupID)
	return i, err
}

const deleteUserGroup = `-- name: DeleteUserGroup :one
DELETE FROM users_groups
WHERE group_id = $1 AND user_id = $2
RETURNING id, user_id, group_id
`

type DeleteUserGroupParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteUserGroup(ctx context.Context, arg DeleteUserGroupParams) (UsersGroup, error) {
	row := q.db.QueryRowContext(ctx, deleteUserGroup, arg.GroupID, arg.UserID)
	var i UsersGroup
	err := row.Scan(&i.ID, &i.UserID, &i.GroupID)
	return i, err
}
