-- +goose Up
-- +goose StatementBegin
ALTER TABLE users
ALTER COLUMN id SET DEFAULT GEN_RANDOM_UUID(),
ALTER COLUMN created_at SET DEFAULT NOW(),
ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE groups
ALTER COLUMN id SET DEFAULT GEN_RANDOM_UUID(),
ALTER COLUMN created_at SET DEFAULT NOW(),
ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE users_groups
ALTER COLUMN id SET DEFAULT GEN_RANDOM_UUID();

ALTER TABLE expenses
ALTER COLUMN id SET DEFAULT GEN_RANDOM_UUID();

ALTER TABLE splits
ALTER COLUMN id SET DEFAULT GEN_RANDOM_UUID(),
DROP COLUMN created_at,
DROP COLUMN updated_at;

ALTER TABLE transactions
ALTER COLUMN id SET DEFAULT GEN_RANDOM_UUID();
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE transactions
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE splits
ALTER COLUMN id DROP DEFAULT,
ADD COLUMN created_at TIME NOT NULL,
ADD COLUMN updated_at TIME NOT NULL;

ALTER TABLE expenses
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE users_groups
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE groups
ALTER COLUMN id DROP DEFAULT,
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE users
ALTER COLUMN id DROP DEFAULT,
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN updated_at DROP DEFAULT;
-- +goose StatementEnd
